### ISSUE TITLE
如何使用kotlin运行程序

### ISSUE THREAD

**Issue by yelina123** [equationl/motortest#2]
对于不会用如题语言的小白，如何运行语言
有人会拜托给我发邮件， [squat.flunk-0m@icloud.com](url) ，多谢！

**Comment by yelina123** [comment]
酷安现在崩了

**Comment by equationl** [comment]
下载 Android studio ，打开这个项目，run 就行了

**Comment by yelina123** [comment]
> 下载 Android studio ，打开这个项目，run 就行了

谢谢
